import songs from "../songs.json";

export type Song = {
  artist: string;
  title: string;
  album: string;
  genre: string;
  type?: string;
  id: number;
};

// "Blue Moon",
const playlistForEllen = [
  ["(Love Is Like A) Heat Wave", "Martha Reeves & The Vandellas"],
  ["(Sittin' On) the Dock of the Bay", "Otis Redding"],
  ["(What A) Wonderful World", "Sam Cooke"],
  ["(Your Love Keeps Lifting Me) Higher & Higher", "Jackie Wilson"],
  ["A Change Is Gonna Come", "Sam Cooke"],
  ["A House Is Not a Home", "Luther Vandross"],
  ["Ain't No Mountain High Enough", "Marvin Gaye"],
  ["Ain't No Sunshine", "Bill Withers"],
  ["Ain't That A Shame", "Fats Domino"],
  ["Ain't That Peculiar", "Marvin Gaye"],
  ["Ain't Too Proud To Beg", "The Temptations"],
  ["Baby I Need Your Loving", "Four Tops"],
  ["Baby Love", "The Supremes"],
  ["Be My Baby", "The Ronettes"],
  ["Being With You", "Smokey Robinson"],
  ["Blue Moon", "The Marcels"],
  ["Brick House", "Commodores"],
  ["Chain of Fools", "Aretha Franklin"],
  ["Climbing Higher Mountains", "Aretha Franklin"],
  ["Come Rain or Come Shine", "Ray Charles"],
  ["Dancing In The Street", "Martha Reeves & The Vandellas"],
  ["Dancing Machine", "The Jackson 5"],
  ["Do You Love Me", "The Contours"],
  ["Easy", "Commodores"],
  ["Everybody Plays the Fool - Remastered", "The Main Ingredient"],
  ["Everyday People", "Sly & The Family Stone"],
  ["Finger Poppin' Time", "Hank Ballard & The Midnighters"],
  ["Fingertips", "Stevie Wonder"],
  ["For Once In My Life", "Stevie Wonder"],
  ["Georgia on My Mind - Original Master Recording", "Ray Charles"],
  ["Get Ready", "The Temptations"],
  ["Good Golly Miss Molly", "Little Richard"],
  ["Got To Be There", "Michael Jackson"],
  ["Here and Now", "Luther Vandross"],
  ["Hit the Road Jack", "Ray Charles"],
  ["How I Got Over", "Aretha Franklin"],
  ["How Sweet It Is (To Be Loved By You)", "Marvin Gaye"],
  ["I Can't Get Next To You", "The Temptations"],
  ["I Can't Help Myself (Sugar Pie, Honey Bunch)", "Four Tops"],
  ["I Got a Woman", "Ray Charles"],
  ["I Got You (I Feel Good)", "James Brown & The Famous Flames"],
  ["I Heard It Through The Grapevine", "Marvin Gaye"],
  ["I Put A Spell On You", "Nina Simone"],
  ["I Say a Little Prayer", "Aretha Franklin"],
  ["I Second That Emotion", "Smokey Robinson & The Miracles"],
  ["I Want You Back", "The Jackson 5"],
  ["I Was Made To Love Her", "Stevie Wonder"],
  ["I'll Be Around", "The Spinners"],
  ["I'll Be Doggone", "Marvin Gaye"],
  ["In the Midnight Hour", "Wilson Pickett"],
  ["Jimmy Mack", "Martha Reeves & The Vandellas"],
  ["Just My Imagination (Running Away With Me)", "The Temptations"],
  ["Just the Two of Us", "Grover Washington, Jr."],
  ["Knock on Wood", "Eddie Floyd"],
  ["Lady", "Lionel Richie"],
  ["Lady Love", "Lou Rawls"],
  ["Land of 1000 Dances", "Wilson Pickett"],
  ["Lean on Me", "Bill Withers"],
  ["Let's Stay Together", "Al Green"],
  ["Little Bitty Pretty One", "Thurston Harris"],
  ["Love Train", "The O'Jays"],
  ["Midnight Train to Georgia", "Gladys Knight & The Pips"],
  ["Money And Me", "Barrett Strong"],
  ["My Girl", "The Temptations"],
  ["My Guy", "Mary Wells"],
  ["Nightshift", "Commodores"],
  ["On Broadway", "George Benson"],
  ["One Hundred Ways", "Quincy Jones"],
  ["Papa Was A Rollin' Stone", "The Temptations"],
  ["Please Mr. Postman", "The Marvelettes"],
  ["Please, Please, Please", "James Brown & The Famous Flames"],
  ["Precious Lord", "Al Green"],
  ["Reach Out I'll Be There", "Four Tops"],
  ["Rescue Me", "Fontella Bass"],
  ["Respect", "Aretha Franklin"],
  ["Rock with You", "Michael Jackson"],
  ["Rockin' Robin", "Michael Jackson"],
  ["Shop Around", "The Miracles"],
  ["Shout, Pts. 1 & 2", "The Isley Brothers"],
  ["Signed, Sealed, Delivered (I'm Yours)", "Stevie Wonder"],
  ["Smoke Gets In Your Eyes", "The Platters"],
  ["So Much In Love", "The Tymes"],
  ["Soul Man", "Sam & Dave"],
  ["Stop! In The Name Of Love", "The Supremes"],
  ["Stuck On You", "Lionel Richie"],
  ["Superstition", "Stevie Wonder"],
  ["The Book of Love", "The Monotones"],
  ["The Locomotion", "Little Eva"],
  ["Rubberband Man", "The Spinners"],
  ["The Tears Of A Clown", "Smokey Robinson & The Miracles"],
  ["The Tracks Of My Tears", "Smokey Robinson & The Miracles"],
  ["The Twist", "Chubby Checker"],
  ["The Way You Do The Things You Do", "The Temptations"],
  ["These Arms of Mine", "Otis Redding"],
  ["Think", "Aretha Franklin"],
  ["This Magic Moment", "The Drifters"],
  ["This Old Heart Of Mine (Is Weak For You)", "The Isley Brothers"],
  ["Three Times A Lady", "Commodores"],
  ["Tired of Being Alone", "Al Green"],
  ["Try Me", "James Brown"],
  ["Tutti-Frutti", "Little Richard"],
  ["Twistin' the Night Away", "Sam Cooke"],
  ["Under the Boardwalk", "The Drifters"],
  ["Uptight (Everything's Alright)", "Stevie Wonder"],
  ["Use Ta Be My Girl", "The O'Jays"],
  ["What a Friend We Have in Jesus", "Aretha Franklin"],
  ["What Becomes Of The Brokenhearted", "Jimmy Ruffin"],
  ["What's Going On", "Marvin Gaye"],
  ["When a Man Loves a Woman", "Percy Sledge"],
  ["Where Did Our Love Go", "The Supremes"],
  ["You Can't Hurry Love", "The Supremes"],
  ["You Don't Know Me", "Ray Charles"],
  ["You Send Me", "Sam Cooke"],
  ["You'll Lose A Good Thing", "Barbara Lynn"],
  ["You'll Never Find Another Love Like Mine", "Lou Rawls"],
  ["You're All I Need To Get By", "Marvin Gaye"],
  ["You're The First, The Last, My Everything ", "Barry White"],
  ["You've Really Got A Hold On Me", "The Miracles"],
];

export const preselectedSongLists: { [key: string]: string[] } = {
  "60s Rock": [
    "Like a Rolling Stone",
    "Hey Jude",
    "Paint It, Black",
    "A Day in the Life",
    "Light My Fire",
    "All Along the Watchtower",
    "Purple Haze",
    "Whole Lotta Love",
    "Born to Be Wild",
    "Fortunate Son",
    "White Rabbit",
    "Gimme Shelter",
    "Somebody to Love",
    "I Want to Hold Your Hand",
    "Sunshine of Your Love",
    "Satisfaction",
    "California Dreamin'",
    "For What It's Worth",
    "Piece of My Heart",
    "My Generation",
  ],
  "70s Rock": [
    "Stairway to Heaven",
    "Bohemian Rhapsody",
    "Hotel California",
    "Dream On",
    "Smoke on the Water",
    "Free Bird",
    "Layla",
    "Imagine",
    "Baba O'Riley",
    "Born to Run",
    "More Than a Feeling",
    "We Will Rock You",
    "Sweet Home Alabama",
    "American Woman",
    "Barracuda",
    "Go Your Own Way",
    "Riders on the Storm",
    "Another Brick in the Wall",
    "Walk This Way",
    "The Joker",
  ],
  "60s Country": [
    "Ring of Fire",
    "Stand by Your Man",
    "Crazy",
    "Okie from Muskogee",
    "Coal Miner's Daughter",
    "Folsom Prison Blues",
    "El Paso",
    "The Ballad of Jed Clampett",
    "Harper Valley PTA",
    "I Fall to Pieces",
    "King of the Road",
    "Mama Tried",
    "Gentle on My Mind",
    "Act Naturally",
    "Detroit City",
    "I Walk the Line",
    "Blue Moon of Kentucky",
    "The Race Is On",
    "Hello Walls",
    "I Can't Stop Loving You",
  ],
  "70s Country": [
    "The Gambler",
    "On the Road Again",
    "Take Me Home, Country Roads",
    "Blue Eyes Crying in the Rain",
    "He Stopped Loving Her Today",
    "Rhinestone Cowboy",
    "Delta Dawn",
    "Amarillo by Morning",
    "Luckenbach, Texas (Back to the Basics of Love)",
    "If You've Got the Money I've Got the Time",
    "The Devil Went Down to Georgia",
    "Before the Next Teardrop Falls",
    "Help Me Make It Through the Night",
    "Rose Garden",
    "Behind Closed Doors",
    "It Was Almost Like a Song",
    "You're the Reason God Made Oklahoma",
    "Family Tradition",
    "Tennessee Whiskey",
    "Don't It Make My Brown Eyes Blue",
  ],
  "60s Jazz": [
    "So What",
    "Take Five",
    "My Favorite Things",
    "A Love Supreme",
    "Blue Train",
    "Song for My Father",
    "Maiden Voyage",
    "The Girl from Ipanema",
    "Cantaloupe Island",
    "Watermelon Man",
    "Mercy, Mercy, Mercy",
    "Footprints",
    "St. Thomas",
    "All Blues",
    "Naima",
    "Work Song",
    "One Note Samba",
    "Summertime",
    "Afro Blue",
    "Straight, No Chaser",
  ],
  "70s Jazz": [
    "Chameleon",
    "Spain",
    "Birdland",
    "Mr. Magic",
    "Black Byrd",
    "Cantaloupe Island",
    "Red Clay",
    "Feels So Good",
    "The Black Angel",
    "Night in Tunisia",
    "Watermelon Man",
    "Aja",
    "Freddie Freeloader",
    "The Chicken",
    "Feels So Good",
    "Nica's Dream",
    "The Sidewinder",
    "Butterfly",
    "Driftin'",
    "Joy Spring",
  ],
};

export const preselectedSongListsArr: { [key: string]: string[][] } = {
  "Soulful Sounds": playlistForEllen,
};

let uniqueSongs: { [key: string]: Song } = {};

songs.forEach((song) => {
  const { title, artist, album, genre } = song;
  const key = `${title.toLowerCase()}-${artist.toLowerCase()}-${album.toLowerCase()}`;

  if (!uniqueSongs[key]) {
    uniqueSongs[key] = song;
  } else if (uniqueSongs[key].genre !== genre) {
    // If the genre is different, update the genre to the first encountered genre
    uniqueSongs[key].genre = genre;
  }
});

// Convert the object back to an array
export const itunesSongs: Song[] = Object.values(uniqueSongs);
