export const artistList = [
{ label: `Faron Young` },
{ label: `George Jones` },
{ label: `Hank Williams` },
{ label: `Johnny Cash` },
{ label: `Patsy Cline` },
{ label: `Patti Page` },
{ label: `Kitty Wells` },
{ label: `Jim Reeves` },
{ label: `Chet Atkins` },
{ label: `Ray Price` },
{ label: `Marty Robbins` },
{ label: `Conway Twitty` },
{ label: `Glen Campbell` },
{ label: `Loretta Lynn` },
{ label: `Merle Haggard` },
{ label: `Tammy Wynette` },
{ label: `Buck Owens` },
{ label: `Roger Miller` },
{ label: `Charley Pride` },
{ label: `Dolly Parton` },
{ label: `Kenny Rogers` },
{ label: `Willie Nelson` },
{ label: `Hank Williams, Jr` },
{ label: `Waylon Jennings` },
{ label: `Emmylou Harris` },
{ label: `Alabama` },
{ label: `Reba McEntire` },
{ label: `Randy Travis ` },
{ label: `Bing Crosby` },
{ label: `Frank Sinatra` },
{ label: `Perry Como` },
{ label: `Vaughan Monroe` },
{ label: `Judy Garland` },
{ label: `Mills Brothers` },
{ label: `Kingston Trio` },
{ label: `Bobby Darin` },
{ label: `Dean Martin` },
{ label: `Jim Reeves` },
{ label: `Johnny Mathis` },
{ label: `Nat King Cole` },
{ label: `Tony Bennett` },
{ label: `Connie Francis` },
{ label: `Doris Day` },
{ label: `Edith Piaf` },
{ label: `Rosemary Clooney` },
{ label: `Joni Mitchell` },
{ label: `Judy Collins` },
{ label: `Simon & Garfunkel` },
{ label: `The Monkees` },
{ label: `The 5th Dimension` },
{ label: `Andy Williams` },
{ label: `Jimmy Roselli` },
{ label: `Barbara Streisand` },
{ label: `Bobby Vinton` },
{ label: `Burt Bacharach` },
{ label: `Dionne Warwick` },
{ label: `Englebert Humperdinck` },
{ label: `Righteous Brothers` },
{ label: `Tom Jones` },
{ label: `Carly Simon` },
{ label: `Carole King` },
{ label: `Gordon Lightfoot` },
{ label: `James Taylor` },
{ label: `Jim Croce` },
{ label: `Neil Diamond` },
{ label: `Jimmy Buffet` },
{ label: `Jackson 5` },
{ label: `Rod Stewart` },
{ label: `ABBA` },
{ label: `John Denver` },
{ label: `Paul Simon` },
{ label: `The Carpenters` },
{ label: `Whitney Houston` },
{ label: `Gloria Estefan` },
{ label: `Lionel Ritchie` },
{ label: `Michael Jackson` },
{ label: `Rick Astley` },
{ label: `Kenny G` },
{ label: `Billy Joel ` },
{ label: `Bill Haley` },
{ label: `Buddy Holly` },
{ label: `Chuck Berry` },
{ label: `Elvis Presley` },
{ label: `Fats Domino` },
{ label: `Little Richard` },
{ label: `Ritchie Valens` },
{ label: `Everly Brothers` },
{ label: `The Platters` },
{ label: `Sam Cooke` },
{ label: `Jackie Wilson` },
{ label: `The Drifters` },
{ label: `James Brown` },
{ label: `Beach Boys` },
{ label: `Bee Gees` },
{ label: `Beatles` },
{ label: `Chubby Checker` },
{ label: `Creedence Clearwater` },
{ label: `Linda Ronstadt` },
{ label: `Mamas & Papas` },
{ label: `Crosby, Stills, Nash` },
{ label: `Eric Clapton` },
{ label: `Frankie Valli` },
{ label: `Four Seasons` },
{ label: `Jerry Lee Lewis` },
{ label: `Rolling Stones` },
{ label: `Roy Orbison` },
{ label: `The Band` },
{ label: `Bob Dylan` },
{ label: `The Velvet Underground` },
{ label: `Bread` },
{ label: `Chicago` },
{ label: `Elton John` },
{ label: `Bruce Springsteen` },
{ label: `Doobie Brothers` },
{ label: `Eagles` },
{ label: `Fleetwood Mac` },
{ label: `John Lennon` },
{ label: `Queen` },
{ label: `Steve Miller Band` },
{ label: `Tom Petty` },
{ label: `Boston` },
{ label: `Heart` },
{ label: `Lynyrd Skynrd` },
{ label: `Pink Floyd` },
{ label: `David Bowie` },
{ label: `The Allman Brothers` },
{ label: `Three Dog Night` },
{ label: `Bob Segar` },
{ label: `Led Zeppelin` },
{ label: `Aerosmith` },
{ label: `Air Supply` },
{ label: `Daryl Hall & John Oates` },
{ label: `The Cars` },
{ label: `Dire Straits` },
{ label: `Bon Jovi` },
{ label: `ZZ Top` },
{ label: `Bob Dylan` },
{ label: `Clancy Brothers` },
{ label: `Doc Watson` },
{ label: `Irish Rovers` },
{ label: `Pete Seeger` },
{ label: `Peter, Paul & Mary` },
{ label: `Joan Baez` },
{ label: `Al Green` },
{ label: `Aretha Franklin` },
{ label: `Ben E King` },
{ label: `Commodores` },
{ label: `Diana Ross` },
{ label: `Four Tops` },
{ label: `Gladys Knight` },
{ label: `Lou Rawls` },
{ label: `Martha Reeves` },
{ label: `Marvin Gaye` },
{ label: `O'Jays` },
{ label: `Otis Redding` },
{ label: `Ray Charles` },
{ label: `Smokey Robinson` },
{ label: `Stevie Wonder` },
{ label: `The Temptations` },
{ label: `Aaron Neville` },
{ label: `Barry White` },
{ label: `Percy Sledge` },
{ label: `Celia Cruz` },
{ label: `El Gran Combo de Puerto Rico` },
{ label: `Javier Solis` },
{ label: `Julio Iglesias` },
{ label: `Leo Dan` },
{ label: `Los Panchos` },
{ label: `Roberto Carlos` },
{ label: `Tito Puente` },
{ label: `Willie Colon` },
{ label: `B.B. King` },
{ label: `Bob Marley` },
{ label: `Muddy Waters` },
{ label: `Albertina Walker` },
{ label: `Andrae Crouch` },
{ label: `Aretha Franklin` },
{ label: `Bill & Gloria Gaithers` },
{ label: `CeCe Winans` },
{ label: `Edwin Hawkins Singers` },
{ label: `Elvis Presley` },
{ label: `George Beverly Shea` },
{ label: `Mahalia Jackson` },
{ label: `Mormon Tabernacle Choir` },
{ label: `Randy Travis` },
{ label: `Rev James Cleveland` },
{ label: `Shirley Caesar ` },
{ label: `The Cathedrals` },
{ label: `Zion Harmonizers` },
{ label: `The Canton Spirituals` },
{ label: `Alan Jackson` },
{ label: `Walter Hawkins` },
{ label: `The Williams Brothers` },
{ label: `Billie Holiday` },
{ label: `Dinah Washington` },
{ label: `Ella Fitzgerald` },
{ label: `Etta James` },
{ label: `Julie London` },
{ label: `Louis Armstrong` },
{ label: `Nancy Wilson` },
{ label: `Nat King Cole` },
{ label: `Nina Simone` },
{ label: `Pearl Bailey` },
{ label: `Sarah Vaughan` },
{ label: `The Ink Spots` },
{ label: `Art Tatum` },
{ label: `Charlie Parker` },
{ label: `Dizzy Gillespie` },
{ label: `Gene Krupa` },
{ label: `George Shearing` },
{ label: `Herb Alpert` },
{ label: `Herbie Mann` },
{ label: `John Coltrane` },
{ label: `Lionel Hampton` },
{ label: `Miles Davis` },
{ label: `Quincy Jones` },
{ label: `Thelonious Monk` },
{ label: `Camelot` },
{ label: `Cats` },
{ label: `Fiddler on the Roof` },
{ label: `Guys & Dolls` },
{ label: `Les Miserables` },
{ label: `Mary Poppins` },
{ label: `My Fair Lady` },
{ label: `Oklahoma` },
{ label: `Phantom of the Opera` },
{ label: `Pippin` },
{ label: `Sound of Music` },
{ label: `South Pacific` },
{ label: `The Music Man` },
{ label: `Grease` },
{ label: `The King and I` },
{ label: `Westside Story` },
{ label: `Artie Shaw` },
{ label: `Benny Goodman` },
{ label: `Cab Calloway` },
{ label: `Count Basie` },
{ label: `Duke Ellington` },
{ label: `Glenn Miller` },
{ label: `Lawrence Welk` },
{ label: `Tommy Dorsey` },
{ label: `Bach` },
{ label: `Beethoven` },
{ label: `Boston Pops` },
{ label: `Chopin` },
{ label: `Handel` },
{ label: `Haydn` },
{ label: `Leonard Bernstein` },
{ label: `Mahler` },
{ label: `Schumann` },
{ label: `Tchaikovsky` },
{ label: `Vivaldi` },
{ label: `Vladimir Horowitz` },
{ label: `Yo-Yo Ma` },
{ label: `Mozart` },
{ label: `Andrea Bocelli` },
{ label: `Luciano Pavarotti` },
{ label: `The Three Tenors` },
{ label: `Barry White` },
{ label: `Donna Summer` },
{ label: `Earth, Wind & Fire` },
{ label: `KC & the Sunshine Band` },
{ label: `Kool & the Gang` },
{ label: `Village People` },
{ label: `Bee Gees` },
{ label: `Chairmen of the Board` },
{ label: `The Embers` }]